# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-15 04:57
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_markdownmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkDownModel',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
