# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-15 05:04
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20181015_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=mdeditor.fields.MDTextField(default='', verbose_name='正文'),
        ),
    ]
