# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-15 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_counts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counts',
        ),
    ]
